chore: Changes for release build job
GoogleCloudPlatform/google-cloud-spanner-hibernate pull request #454
Opened 2022-07-07 15:49 UTC by ddixit14

2022-07-07 18:08 UTC, ddixit14 commented
> Why remove the release profile? It prevents samples and test project from getting released.
> 
> https://github.com/GoogleCloudPlatform/google-cloud-spanner-hibernate/blob/master/pom.xml#L304-L306

Sorry, it was by mistake. I actually intended to include the profile in the promote release part of the script, since the modules being processed in both the staging and releasing scripts were different.

2022-07-07 18:10 UTC, elefeint requested changes
Do you need to specify the staging repository? In the old process, stage.sh sent all releasable artifacts to Sonatype, and then promote.sh triggered the publishing of those artifacts. This was all tied together by the "staging repository ID" -- the thing that you'd find in the staging logs and provide to the release/promote job.

The current [promote.sh](https://github.com/GoogleCloudPlatform/google-cloud-spanner-hibernate/blob/fabbc81e3924b1f12658760c5bf3e25eb0ecba4d/.kokoro/promote.sh#L39) passes `-DstagingRepositoryId=${STAGING_REPOSITORY_ID}` to let sonatype know which pre-staged directory to publish. What is the new process meant to do -- release in one step, or stage-and-release like before just with a single script?

2022-07-07 18:52 UTC, suztomo approved these changes
Approving. Don't forget to answer Elena's question.

2022-07-07 18:52 UTC, suztomo commented on .kokoro/stage.sh
> +    -P release
The missing problem. The 2nd command was trying to release the integration test module.

2022-07-07 18:56 UTC, elefeint commented
We've looked at it offline, and it looks like `mvn deploy` stages it first locally, and then remotely at Sonatype, generating the staging repository ID along the way. Then `mvn nexus-release` takes the already-staged files and the (cached?) staging repository ID and allows promotion of staged artifacts to released ones.

2022-07-11 19:24 UTC, ddixit14 commented
@elefeint can you please approve this so I can merge it in?

2022-07-11 19:35 UTC, elefeint requested changes

2022-07-11 19:35 UTC, elefeint commented on pom.xml
> +            <serverId>sonatype-nexus-staging</serverId>
I'd keep `ossrh` in all three instances, unless there is a reason to change repository ID.

2022-07-12 17:33 UTC, elefeint approved these changes

2022-07-12 17:38 UTC, merged