Adding annotations for snapshot version bumps in pom.xml's
GoogleCloudPlatform/google-cloud-spanner-hibernate pull request #459
Opened 2022-07-12 17:02 UTC by ddixit14

This PR is for adding annotations in various pom.xml's so that the release-please snapshot PR can bump the versions wherever required. 
For identifying which pom.xml's need this bump, I have referred to the last manual snapshot bump release [PR](https://github.com/GoogleCloudPlatform/google-cloud-spanner-hibernate/pull/389).

2022-07-12 17:46 UTC, elefeint requested changes
What is the significance of `google-cloud-spanner-hibernate-samples` vs `google-cloud-spanner-hibernate`? The versions are generally the same.

2022-07-12 17:46 UTC, elefeint commented on google-cloud-spanner-hibernate-samples/pom.xml
> +		<version>1.5.4</version><!-- {x-version-update:google-cloud-spanner-hibernate:current} -->
should this one have `-samples` suffix?

2022-07-12 17:50 UTC, ddixit14 commented
> What is the significance of `google-cloud-spanner-hibernate-samples` vs `google-cloud-spanner-hibernate`? The versions are generally the same.



> What is the significance of `google-cloud-spanner-hibernate-samples` vs `google-cloud-spanner-hibernate`? The versions are generally the same.

I don't have much idea in this...I have just done what was followed the last time. You can suggest me how to go about it.

2022-07-13 13:54 UTC, elefeint requested changes
Well, `/versions.txt` almost definitely needs to match these annotations. Currently, the `/versions.txt` file only contains `google-cloud-spanner-hibernate`, so it won't be able to find a version for `google-cloud-spanner-hibernate-samples`.

Beyond that, it looks like some projects ([bigquery](https://github.com/googleapis/java-bigquery/blob/main/versions.txt)) use a single configuration line for all releasable modules, and then have a static [placeholder/experimental version](https://github.com/googleapis/java-bigquery/blob/3507bf7c9fc2aef299d06d9771cfcc06e3080b87/samples/pom.xml#L22) for samples.

Other projects, such as logging, have [different configuration lines](https://github.com/googleapis/java-logging/blob/main/versions.txt) for different releasable modules. Similarly to logging, this one also has an [unreleasable, un-updateable version for samples](https://github.com/googleapis/java-logging/blob/71dc1ee5ee98532958ea89f4ee7e3dd801d57501/samples/pom.xml#L6).

I would say that we should stick to a single version in `versions.txt`, like you have right now. As it happens, this project only has one releasable module (the dialect itself). I do like the idea of changing all samples to version `0.0.1-SNAPSHOT` and never updating them.

2022-07-13 20:12 UTC, ddixit14 commented
> Well, `/versions.txt` almost definitely needs to match these annotations. Currently, the `/versions.txt` file only contains `google-cloud-spanner-hibernate`, so it won't be able to find a version for `google-cloud-spanner-hibernate-samples`.
> 
> Beyond that, it looks like some projects ([bigquery](https://github.com/googleapis/java-bigquery/blob/main/versions.txt)) use a single configuration line for all releasable modules, and then have a static [placeholder/experimental version](https://github.com/googleapis/java-bigquery/blob/3507bf7c9fc2aef299d06d9771cfcc06e3080b87/samples/pom.xml#L22) for samples.
> 
> Other projects, such as logging, have [different configuration lines](https://github.com/googleapis/java-logging/blob/main/versions.txt) for different releasable modules. Similarly to logging, this one also has an [unreleasable, un-updateable version for samples](https://github.com/googleapis/java-logging/blob/71dc1ee5ee98532958ea89f4ee7e3dd801d57501/samples/pom.xml#L6).
> 
> I would say that we should stick to a single version in `versions.txt`, like you have right now. As it happens, this project only has one releasable module (the dialect itself). I do like the idea of changing all samples to version `0.0.1-SNAPSHOT` and never updating them.

I think you are correct. We can go ahead with a "0.0.1-SNAPSHOT" for all the samples.

2022-07-14 16:08 UTC, elefeint requested changes
As discussed, let's back out the changes to `0.0.1-SNAPSHOT` that I originally recommended. We can d o it at a later point. 

Instead, use a consistent comment `<!-- {x-version-update:google-cloud-spanner-hibernate:current} -->` on every version `1.5.4`.

2022-07-14 16:08 UTC, elefeint commented on google-cloud-spanner-hibernate-samples/basic-hibernate-sample/pom.xml
> +    <artifactId>google-cloud-spanner-hibernate</artifactId>
The parent should be `-samples`.

2022-07-14 16:08 UTC, elefeint commented on google-cloud-spanner-hibernate-samples/basic-hibernate-sample/pom.xml
> +  <url>https://github.com/GoogleCloudPlatform/google-cloud-spanner-hibernate</url>
Is this a new field?

2022-07-14 16:08 UTC, elefeint commented on google-cloud-spanner-hibernate-samples/basic-spanner-features-sample/pom.xml
> +    <version>0.0.1-SNAPSHOT</version><!-- This artifact should not be released  -->
Let's keep 1.5.4 with the instruction to release infrastructure to keep it up to date (`<!-- {x-version-update:google-cloud-spanner-hibernate:current} -->` for now. We'll switch to 0.0.1 at some later point.

2022-07-14 16:08 UTC, elefeint commented on google-cloud-spanner-hibernate-samples/pom.xml
> +		<version>1.5.4</version><!-- {x-version-update:google-cloud-spanner-hibernate:current} -->
Discussed offline; all versions will be synchronized on a single `google-cloud-spanner-hibernate:current` version in the release infrastructure comment.

2022-07-15 20:38 UTC, elefeint approved these changes

2022-07-18 18:48 UTC, merged